title: Universität der Bundeswehr
author: Syslab.com GmbH
brand: unibw
baseurl:
domain: www.unibw.de
media: media
markdown: kramdown
permalink: /:title.html
sass:
#  style: :compressed
  load_paths:
    - css
    - js
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - node_modules
  - Makefile
  - README.md
  - bower.json
  - main.js
  - bundle-config.js
  - src/
  - stamp-bower
  - stamp-npm
  - stamp-bundler
  - ruby/
  - bin/
  - Gruntfile.js
  - package.json
